SW-276-fix-the-ros-walk-forward-example
bdaiinstitute/spot_ros2 pull request #105
Opened 2023-07-11 20:51 UTC by bhung-bdai

The namespace for the robot wasn't included, causing an error where it wouldn't find the ROS topic it was supposed to publish to. I've added it to the example as a command line argument to pass in and updated the README

2023-07-11 20:53 UTC, jbarry-bdai reviewed
Actually this one is supposed to be very simple and work without a robot name... was it broken if you follow the README instructions?  Many places don't use the name prefix because they only have one Spot so I've been trying to preserve that functionality.

2023-07-11 20:58 UTC, bhung-bdai commented
> Actually this one is supposed to be very simple and work without a robot name... was it broken if you follow the README instructions? Many places don't use the name prefix because they only have one Spot so I've been trying to preserve that functionality.

Not exactly. The issue happens when bdai spot_driver launches, since that provides a namespace and it accordingly renames the ROS transforms. I can avoid launching that way if that's the intention but you can always provide no robot name. I just figured that most of us are launching with namespace, so it makes more sense to provide it as an option

2023-07-11 21:01 UTC, bhung-bdai commented
Should we leave it the way it is or optionally pass in a name?

2023-07-11 21:06 UTC, jbarry-bdai commented
> Should we leave it the way it is or optionally pass in a name?

I went back and forth on that and decided not to have that option because it made it a little more complicated and I was trying to keep it as simple as possible because it's an example.  What would be really good though would be to add another example showing how to use the robot prefix and how to visualize that in rviz and everything.  I wanted to do that but didn't get around to it...

2023-07-11 21:21 UTC, bhung-bdai commented
I'll try nixing this change and doing a quick double check if it works 100%
following the readme tomorrow then. I was having some issues on the core-io
without namespace l but they might have been resolved in my install.

Brandon

On Tue, Jul 11, 2023, 5:06 PM jbarry-bdai ***@***.***> wrote:

> Should we leave it the way it is or optionally pass in a name?
>
> I went back and forth on that and decided not to have that option because
> it made it a little more complicated and I was trying to keep it as simple
> as possible because it's an example. What would be really good though would
> be to add another example showing how to use the robot prefix and how to
> visualize that in rviz and everything. I wanted to do that but didn't get
> around to it...
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bdaiinstitute/spot_ros2/pull/105#issuecomment-1631509358>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BAW5F4MT4VGATZH3BSHACIDXPW56FANCNFSM6AAAAAA2GRMABQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-11 21:33 UTC, jbarry-bdai commented
I would definitely try this on a laptop before using the core i/o.  it's possible it is broken!  we're not as good as we should be about running these examples with change to the driver.

2023-07-19 15:42 UTC, bhung-bdai commented
Reopening this because it's a small change and improves quality of life if you need to test different setups. Now both ROS examples work with and without a namespace

2023-07-20 14:02 UTC, amessing-bdai requested changes

2023-07-20 14:02 UTC, amessing-bdai commented on examples/simple_walk_forward/README.md
> +ros2 run simple_walk_forward walk_forward --robot <spot_name>
Since the example now works with or without a robot name that should be explained here.

2023-07-20 14:02 UTC, amessing-bdai commented on examples/simple_walk_forward/README.md
> +ros2 run simple_walk_forward walk_forward --robot <spot_name>
Should also be done in the readme for simple_arm_motion

2023-07-20 21:44 UTC, amessing-bdai approved these changes

2023-07-21 14:05 UTC, merged