Spot tour guide functionalities
bdaiinstitute/spot_ros2 pull request #116
Opened 2023-07-28 20:58 UTC by fengjun-yang1

Added functionalities:
- service MovePTZ: set the pan, tilt, zoom (ptz) of the payload Spot CAM
- service GetPTZ: get current pan, tile, zoom of the Spot CAM
- action NavigateToDynamic: navigation with dynamic speed

Added parameter in spot_ros.yaml:
- bool enable_payload_cam: we added this because we realized that decoding the incoming image stream from the payload cam is compute intensive. Without this variable, the image streaming will start automatically. This variable serves as a flag to turn off image streaming from the payload camera.

2023-08-03 13:31 UTC, myeatman-bdai requested changes
I would rename everything that references PTZ to mention something like "SpotCamPTZ". Looks good otherwise.

2023-08-08 13:53 UTC, amessing-bdai requested changes

2023-08-08 13:53 UTC, amessing-bdai commented on spot_driver/spot_driver/spot_ros2.py
> +            enable_payload_cam: Parameter = self.get_parameter("enable_payload_cam").value
Can this parameter be added to `spot_driver/config/spot_ros_example.yaml`?

2023-08-08 13:53 UTC, amessing-bdai commented on spot_driver/spot_driver/spot_ros2.py
> +                try:
Is the try/except a check for whether the robot has a spot cam? If so, can a comment be added that explains this? Also, a warning should probably be logged that says the user enabled the spot cam, but the robot does not have one.

2023-08-08 13:53 UTC, amessing-bdai commented on spot_driver/spot_driver/spot_ros2.py
> +        feedback_thread = threading.Thread(target=self.handle_navigate_to_dynamic_feedback, args=())
Is there a way to do this without creating a separate thread for feedback? There are already some threading bottlenecks that we are working on improving

2023-12-05 17:37 UTC, closed without merging