[SW-684] Update spot_ros2 metadata
bdaiinstitute/spot_ros2 pull request #270
Opened 2024-02-16 17:57 UTC by tcappellari-bdai

## Change Overview

Please include a summary of the changes made and the relevant ticket or issue.

## Testing Done

Please create a checklist of tests you plan to do and check off the ones that have been completed successfully. Ensure that ROS 2 tests use `domain_coordinator` to prevent port conflicts. Further guidance for testing can be found on the [ros utilities wiki](https://github.com/bdaiinstitute/ros_utilities/wiki/Testing-guidelines).

2024-02-16 17:57 UTC, tcappellari-bdai commented
Current dependencies on/for this PR:
* `main`
  * **PR #270** <a href="https://app.graphite.dev/github/pr/bdaiinstitute/spot_ros2/270?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/bdaiinstitute/spot_ros2/270?utm_source=stack-comment).

2024-02-16 19:06 UTC, amessing-bdai commented on spot_description/package.xml
> +  <maintainer email="engineering@theaiinstitute.com">BD AI Institute</maintainer>
```suggestion
  <maintainer email="engineering@theaiinstitute.com">The AI Institute</maintainer>
```

2024-02-16 19:06 UTC, amessing-bdai commented on spot_msgs/LICENSE
> +Copyright (c) 2023 Boston Dynamics AI Institute
```suggestion
Copyright (c) 2023-2024 Boston Dynamics AI Institute
```

2024-02-16 19:20 UTC, khughes-bdai requested changes
Noticed there are still some missing licenses in the packages in the `examples` directory, could those be added too?

2024-02-16 20:36 UTC, khughes-bdai approved these changes
LGTM

2024-02-16 20:42 UTC, amessing-bdai commented on examples/inverse_kinematics_example/package.xml
> +  <maintainer email="gremigi@theaiinstitute.com">AI Institute</maintainer>
```suggestion
  <maintainer email="engineering@theaiinstitute.com">AI Institute</maintainer>
```

2024-02-20 21:56 UTC, bhung-bdai approved these changes

2024-02-20 21:58 UTC, merged