[SW-704] Remove special case for arm0.wr1 in spot_ros2
bdaiinstitute/spot_ros2 pull request #288
Opened 2024-02-29 19:50 UTC by tcappellari-bdai

## Change Overview

Please include a summary of the changes made and the relevant ticket or issue.

## Testing Done

Please create a checklist of tests you plan to do and check off the ones that have been completed successfully. Ensure that ROS 2 tests use `domain_coordinator` to prevent port conflicts. Further guidance for testing can be found on the [ros utilities wiki](https://github.com/bdaiinstitute/ros_utilities/wiki/Testing-guidelines).

2024-02-29 19:51 UTC, tcappellari-bdai commented
Current dependencies on/for this PR:
* **#288** <a href="https://app.graphite.dev/github/pr/bdaiinstitute/spot_ros2/288?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/bdaiinstitute/spot_ros2/288?utm_source=stack-comment).

2024-02-29 20:22 UTC, khughes-bdai approved these changes
LGTM

2024-03-01 14:21 UTC, jbarry-bdai requested changes
I should have put this in the issue but here's the specific test to run to make sure that they really did fix this issue:
1. Pull up rviz and visualize the point cloud from spot's hand in the vision frame
2. Move the hand around and ensure that the point cloud does not move around in the world and that link_wr1 tracks the hand correctly
3. Print the list of static transforms this is creating and ensure that there is a transform from link_wr1 to the camera frames and _not_ a link from body to link_wr1.  If there is that link then we need to add it to excluded frames.

2024-03-05 22:38 UTC, tcappellari-bdai commented
> I should have put this in the issue but here's the specific test to run to make sure that they really did fix this issue:
> 
> 1. Pull up rviz and visualize the point cloud from spot's hand in the vision frame
> 2. Move the hand around and ensure that the point cloud does not move around in the world and that link_wr1 tracks the hand correctly
> 3. Print the list of static transforms this is creating and ensure that there is a transform from link_wr1 to the camera frames and _not_ a link from body to link_wr1.  If there is that link then we need to add link_wr1 to excluded frames.

@jbarry-bdai the point cloud looks good on rviz (doesn't move with the arm), `arm0.link_wr1` appears to track the hand correctly, and I'm able to get the transforms between `arm0.link_wr1` and the other cameras; however `arm0.link_wr1` still has `body` as its parent frame.

2024-03-13 15:43 UTC, tcappellari-bdai commented
> @jbarry-bdai the point cloud looks good on rviz (doesn't move with the arm), `arm0.link_wr1` appears to track the hand correctly, and I'm able to get the transforms between `arm0.link_wr1` and the other cameras; however `arm0.link_wr1` still has `body` as its parent frame.

@jbarry-bdai what would you like to do about this? I'm not super familiar with what the initial issue with the frames was that we had implemented the workaround for but everything appears to work fine besides `link_wr1` being a child of `body`

![Screenshot from 2024-03-13 11-39-58](https://github.com/bdaiinstitute/spot_ros2/assets/156013635/a413f722-efe9-40af-86e6-84ceebd360f5)

2024-03-13 20:19 UTC, jbarry-bdai commented on spot_driver/spot_driver/spot_ros2.py
> -                parent_frame = "link_wr1"
Sadly it appears that BD did NOT fix this issue.  This now needs to be "arm0_link_wr1".  Everything else should actually remain.  Sigh.

2024-03-14 17:00 UTC, khughes-bdai commented
@jbarry-bdai looking into adding that to this PR as Tiffany is OOO for the rest of this week

2024-03-14 21:44 UTC, jschornak-bdai commented
> We currently have THREE arm frames in rviz: arm_link_wr1, arm.link_wr1, and link_wr1. We should figure out where they're all coming from and consolidate down to arm_link_wr1. We will also need to fix at least the hand frame hint in SpotBasic, which uses link_wr1.

I think the intended outcome is for the transform chain for the hand cameras to be independent of the forward kinematics for the arm links. `arm_link_wr1` should be from arm forward kinematics calculated by the RobotStatePublisher (the standalone node in the driver launch file), while `link_wr1` should be from the image publisher node.

One thing to try would be running the Spot state publisher on its own (one way to do that is just by commenting out everything else in the launch file) and see if `arm.link_wr1` is published from there. If so we need to come up with a small fix to filter it out.

> I don't think we should be doing this in Python at all any more? Isn't this in C++ now?

We kept the Python-based image publisher functionality as an optional disabled-by-default feature in the driver node. I'd be in favor of fully deprecating it if we're happy with the C++-based image publisher node.

2024-03-14 21:57 UTC, khughes-bdai commented
@jschornak-bdai `arm0.link_wr1` and `link_wr1` are being published in `getTf` from `robot_state.cpp`. I just pushed a change to this PR where the only one of these frames that gets published is `arm_link_wr1`. Should we also leave in `link_wr1`? Pretty sure `arm0.link_wr1` should be taken out as it's not used for anything else

2024-03-26 14:36 UTC, khughes-bdai commented
This is the current status of this PR:
* `arm_link_wr1`: stays
* `arm0.link_wr1`: taken out and replaced by `arm_link_wr1`
*  `link_wr1`: taken out and replaced by `arm_link_wr1`

the only frame that gets published anymore is `arm_link_wr1`. The camera sensors that were previously children of `link_wr1` are now children of `arm_link_wr1`. Additionally the `arm_link_fgr` frame stays as a child of `arm_link_wr1`.

Current TF tree:
![frames_2024-03-14_14.03.32-1.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/Xynj6CBpA3NqqBFfE8Q9/225ca1a8-0d78-4749-b445-78dee88e9113.png)

2024-03-26 16:56 UTC, khughes-bdai approved these changes
Tested on robot and the inverse kinematics example still works with the updated frame, additionally the TF tree looks good (see comments)

2024-03-26 16:58 UTC, tcappellari-bdai commented
> I should have put this in the issue but here's the specific test to run to make sure that they really did fix this issue:
> 
> 1. Pull up rviz and visualize the point cloud from spot's hand in the vision frame
> 2. Move the hand around and ensure that the point cloud does not move around in the world and that link_wr1 tracks the hand correctly
> 3. Print the list of static transforms this is creating and ensure that there is a transform from link_wr1 to the camera frames and _not_ a link from body to link_wr1.  If there is that link then we need to add link_wr1 to excluded frames.

@jbarry-bdai I think this has been addressed. Can you mark it as done?

2024-03-27 17:55 UTC, jbarry-bdai approved these changes
Woohoo!

I wonder why `Kepler/hand` is a child of `Kepler/body` but that's a puzzle for a different time.

2024-03-27 19:05 UTC, merged